{% set version = '2.0.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tolerance
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tolerance_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tolerance/tolerance_{{ version }}.tar.gz
  sha256: 4dca14f2589363500fc4a4004669fe72e69be2a2cd5b9fef1f4fdd28f2b73a00

build:
  merge_build_host: True  # [win]
  noarch: generic
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
    - r-rgl
  run:
    - r-base
    - r-mass
    - r-rgl

test:
  commands:
    - $R -e "library('tolerance')"           # [not win]
    - "\"%R%\" -e \"library('tolerance')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=tolerance
  license: GPL-2.0-or-later
  summary: Statistical tolerance limits provide the limits between which we can expect to find
    a specified proportion of a sampled population with a given level of confidence.  This
    package provides functions for estimating tolerance limits (intervals) for various
    univariate distributions (binomial, Cauchy, discrete Pareto, exponential, two-parameter
    exponential, extreme value, hypergeometric, Laplace, logistic, negative binomial,
    negative hypergeometric, normal, Pareto, Poisson-Lindley, Poisson, uniform, and
    Zipf-Mandelbrot), Bayesian normal tolerance limits, multivariate normal tolerance
    regions, nonparametric tolerance intervals, tolerance bands for regression settings
    (linear regression, nonlinear regression, nonparametric regression, and multivariate
    regression), and analysis of variance tolerance intervals.  Visualizations are also
    available for most of these settings.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - jdtuck
    - conda-forge/r
