github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
bot:
  automerge: true
provider:
  linux_aarch64: default
  win: azure
test: native_and_emulated
